# Generated by Django 6.0.4 on 2026-04-28 23:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0005_programa_remove_categoria_fk'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResenaCertificadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('certificadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.perfilcertificadora')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_certificadoras', to='usuarios.perfilestudiante')),
            ],
            options={
                'verbose_name': 'Reseña de Certificadora',
                'verbose_name_plural': 'Reseñas de Certificadoras',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('estudiante', 'certificadora')},
            },
        ),
        migrations.CreateModel(
            name='ResenaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_programas', to='usuarios.perfilestudiante')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='programas.programa')),
            ],
            options={
                'verbose_name': 'Reseña de Programa',
                'verbose_name_plural': 'Reseñas de Programas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('estudiante', 'programa')},
            },
        ),
    ]
