# Generated by Django 6.0.4 on 2026-04-29 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0002_initial'),
        ('resenas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenacertificadora',
            name='certificadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.perfilcertificadora'),
        ),
        migrations.AddField(
            model_name='resenacertificadora',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_certificadoras', to='usuarios.perfilestudiante'),
        ),
        migrations.AddField(
            model_name='resenaprograma',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_programas', to='usuarios.perfilestudiante'),
        ),
        migrations.AddField(
            model_name='resenaprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='programas.programa'),
        ),
        migrations.AlterUniqueTogether(
            name='resenacertificadora',
            unique_together={('estudiante', 'certificadora')},
        ),
        migrations.AlterUniqueTogether(
            name='resenaprograma',
            unique_together={('estudiante', 'programa')},
        ),
    ]
