# Generated by Django 6.0.4 on 2026-05-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcertificadora',
            name='ruc',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
