# Generated by Django 6.0.4 on 2026-04-29 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_corta', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='programas/')),
                ('duracion_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_semanas', models.PositiveIntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_gratuito', models.BooleanField(default=False)),
                ('otorga_certificado', models.BooleanField(default=True)),
                ('descripcion_certificado', models.CharField(blank=True, max_length=255)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('inscripciones_abiertas', models.BooleanField(default=True)),
                ('url_inscripcion', models.URLField(blank=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='catalogos.categoria')),
            ],
            options={
                'verbose_name': 'Programa',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
