# Generated by Django 6.0.4 on 2026-04-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('programas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='certificadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='usuarios.perfilcertificadora'),
        ),
        migrations.AddField(
            model_name='programa',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='catalogos.estadoprograma'),
        ),
        migrations.AddField(
            model_name='programa',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='catalogos.modalidad'),
        ),
        migrations.AddField(
            model_name='programa',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='catalogos.moneda'),
        ),
        migrations.AddField(
            model_name='programa',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='catalogos.nivelacademico'),
        ),
        migrations.AddField(
            model_name='programa',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='programas', to='catalogos.tag'),
        ),
        migrations.AddField(
            model_name='programa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='catalogos.tipoprograma'),
        ),
    ]
