# Generated by Django 6.0.4 on 2026-04-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Interés',
                'verbose_name_plural': 'Intereses',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
