# Generated by Django 6.0.4 on 2026-04-29 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intereses', '0001_initial'),
        ('programas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interes',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses', to='usuarios.perfilestudiante'),
        ),
        migrations.AddField(
            model_name='interes',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesados', to='programas.programa'),
        ),
        migrations.AlterUniqueTogether(
            name='interes',
            unique_together={('estudiante', 'programa')},
        ),
    ]
